apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: {{ .Values.api.name }}
    {{- include "testcity.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
        {{- include "testcity.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.api.image.repository }}:{{ default .Chart.Version .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.targetPort }}
          env:
            - name: GITLAB_URL
              value: {{ .Values.gitlab.url }}
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab-credentials
                  key: token
            - name: TESTANALYTICS_CLICKHOUSE_HOST
              value: {{ .Values.clickhouse.host }}
            - name: TESTANALYTICS_CLICKHOUSE_PORT
              value: {{ .Values.clickhouse.port | quote }}
            - name: TESTANALYTICS_CLICKHOUSE_DB
              value: {{ .Values.clickhouse.db }}
            - name: TESTANALYTICS_CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: clickhouse-credentials
                  key: user
            - name: TESTANALYTICS_CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-credentials
                  key: password
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otlp.endpoint | quote }}
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  name: oltp-headers
                  key: value
            - name: OTEL_ENVIRONMENT
              value: {{ .Values.global.environment | quote }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers }}
            {{- if .Values.redis.host }}
            - name: REDIS_CONNECTION_STRING
              value: "{{ .Values.redis.host }}:{{ .Values.redis.port }}"
            {{- end }}
            - name: AUTHORIZATION_TYPE
              value: {{ .Values.authorization.type | quote }}
            {{- if or (eq .Values.authorization.type "OpenIdConnect") (eq .Values.authorization.type "OpenIdConnectWithCerberus") }}
            - name: OIDC_AUTHORITY
              value: {{ .Values.authorization.oidc.authority | quote }}
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oidc-credentials
                  key: clientId
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc-credentials
                  key: clientSecret
            {{- end }}
            {{- if eq .Values.authorization.type "OpenIdConnectWithCerberus" }}
            - name: CERBERUS_URL
              value: {{ .Values.cerberus.url | quote }}
            - name: CERBERUS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cerberus-credentials
                  key: apiKey
            - name: CERBERUS_SERVICE
              value: {{ .Values.cerberus.service | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
