{{- if .Values.redis.host }}
apiVersion: v1
kind: Service
metadata:
  name: test-city-redis-service
  labels:
    app: test-city-redis
spec:
  selector:
    app: test-city-redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: 6379
  type: ClusterIP
{{- end }}
